### ISSUE TITLE
Source not showing up on coveralls

### ISSUE THREAD

**Issue by giggio** [coveralls-net/coveralls.net#1]
If you [navigate to a source](https://coveralls.io/files/418371080) on Coveralls.io you see this:

> The file "c:/projects/coveralls-net/Coveralls.Lib/CoverallsBootstrap.cs" isn't available on GitHub. Either it's been removed, or the repo root directory needs to be updated.

![image](https://cloud.githubusercontent.com/assets/334958/5695839/b85ebaae-999b-11e4-8535-3b4cee6ec8e0.png)

**Comment by jdeering** [comment]
Thanks. I've been meaning to get the paths to convert to relative from the working directory (which should be the root of the repository). I can get to this in the next day or two.

If you want to fork and add yourself, feel free. Just let me know if you need any help or direction. Please add unit tests for what you add and submit a Pull Request when ready.

**Comment by giggio** [comment]
Actually, I just found out that coveralls lets me specify those, so I did and it is working: https://coveralls.io/r/code-cracker/code-cracker
So no rush to add that.
