### ISSUE TITLE
Reporting issue

### ISSUE THREAD

**Issue by sawilde** [coveralls-net/coveralls.net#11]
https://coveralls.io/builds/1971297 is showing as 0% but the coverage is [actually 100%](https://ci.appveyor.com/project/sawilde/accountright-live-api-net-sdk) - Is there an issue with the upload tool? Are there any switches I can use to dump out what coveralls.net is uploading/sending to coveralls.io?

**Comment by jdeering** [comment]
I'll add it to the debug option. Or anyone else can if they want. Just pull request it.

**Comment by sawilde** [comment]
I hacked in a small dump to disk and realized the issue was a defect in how opencover merges reports and how coveralls.io is using the affected fields. New release coming soon
