### ISSUE TITLE
Appveyor - OpenCover > Coveralls

### ISSUE THREAD

**Issue by d4nj0nes** [coveralls-net/coveralls.net#23]
Hi - I have asked a similar question over at the Open Cover issues page as I am not sure where the problem lies and I was looking for guidance on best practice on this.
The scenario is that we run OpenCover on appveyor on two assemblies with a filter two include only two specific namespaces. Still the output file is over 100mb.
The generated file is then sent with Coveralls.Net to our coveralls.io repo.
The whole process takes about  20 minutes - partly I imagine due to the generation of the output xml partly the sending the large file (+ sources?) to coveralls via coveralls.net. 
- what are the options if any on sending less information (I have asked Open Cover for guidance on reducing the size of that file)
- we are using the fork at  https://github.com/jdeering/coveralls.net from nuget version 1.25-beta. We updated to 1.3.2 from 1.2.5-beta which gave an error about not finding a `value for SourceDigest in the CoverageFile` . To get around that we added the option for `--full-sources` , but then ultimately reverted back to the 1.2.5-beta. Is this a known issue? Again perhaps a question for Open Cover about the output file formatting
  
  Any help would be appreciated thanks.

**Comment by jdeering** [comment]
You'll definitely want the more up-to-date versions as we added support for sending the source digest to coveralls instead of the full source. I will work on seeing A) what the issue was for getting the SourceDigest value and B) a way to speed up the hashing. 

If the majority of the time is OpenCover, you'll definitely want to get with them to slim it down, but I will work on trying to keep Coveralls.net from being the bottleneck as much as possible.

**Comment by d4nj0nes** [comment]
Thank for your reply. I have had a few pointers from them on this so will try those. We would definitely like to be using the latest version as soon as possible.

**Comment by jdeering** [comment]
Version 1.3.4 has been released. It should resolve the issue with digests that you all were having. If not, it should at least provide more details so we can better narrow down your specific issue.

**Comment by d4nj0nes** [comment]
Thanks that's great - I'll give it a try now...

**Comment by d4nj0nes** [comment]
That worked perfectly and no performance issues. Thanks for the quick turn around!
