### ISSUE TITLE
Build numbers

### ISSUE THREAD

**Issue by richardschneider** [coveralls-net/coveralls.net#26]
I would like the coveralls build number to match the one created by AppVeyor.  I tried setting the --JobId, like this

```
packages\coveralls.net.0.6.0\tools\csmacnz.coveralls.exe --opencover -i ./coverage.xml 
   --jobId %APPVEYOR_BUILD_NUMBER%
```

but it did't work. Here's the [yml](https://github.com/richardschneider/net-ipfs-core/blob/master/appveyor.yml).

**Comment by jdeering** [comment]
Looks like you're using a different package. Please see https://github.com/csmacnz/coveralls.net
