### ISSUE TITLE
NRE in 1.4.1

### ISSUE THREAD

**Issue by Lakritzator** [coveralls-net/coveralls.net#36]
When calling coveralls.net.exe with just the coverage.xml file, the following error occurs:

```
An unknown exception has occurred.
Object reference not set to an instance of an object.
   at Coveralls.Net.CommandLineOptions.get_InputFiles() in C:\Users\jason\src\open-source\coveralls.net\coveralls.net\CommandLineOptions.cs:line 35
   at Coveralls.CoverallsBootstrap.get_CoverageFiles() in C:\Users\jason\src\open-source\coveralls.net\Coveralls.Lib\CoverallsBootstrap.cs:line 102
   at Coveralls.Net.Program.Run(CommandLineOptions options) in C:\Users\jason\src\open-source\coveralls.net\coveralls.net\Program.cs:line 40
   at Coveralls.Net.Program.Main(String[] args) in C:\Users\jason\src\open-source\coveralls.net\coveralls.net\Program.cs:line 18
```

This is like #34, I think it was never solved.

The following line https://github.com/coveralls-net/coveralls.net/blob/master/coveralls.net/Program.cs#L17 is most likely calling the default constructor, not setting the _fileSystem as is done in the other constructor here: https://github.com/coveralls-net/coveralls.net/blob/master/coveralls.net/CommandLineOptions.cs#L21

**Comment by pitermarx** [comment]
I'm having the same issue.
Here is the log.
https://ci.appveyor.com/project/pitermarx/cake-sonarscanner/build/0.1.1-cakeupgrade0031

**Comment by mkoertgen** [comment]
Me, too.

If no objections from your side, i would provide a PR fixing this.

**Comment by mkoertgen** [comment]
Just checking out the code: about 7 tests seem to be broken as NCrunch reports this.

**Comment by mkoertgen** [comment]
PR #37 should be fine, now. Please review and update the NuGet package, if fine.

**Comment by mkoertgen** [comment]
@jdeering Thanks for merging PR #37 and closing this issue.

How about updating the NuGet package at https://www.nuget.org/packages/coveralls.io ?
I could use an updated version 1.4.2.

Is pushing to NuGet a manual process? If so, what about automating the push, e.g. using GitVersion?

**Comment by jdeering** [comment]
It is a manual process for now. I haven't had time to set up the automation for it yet.

The newest version has been uploaded to NuGet and should now be available.

**Comment by mkoertgen** [comment]
Thx @jdeering. Just tested with 1.4.2. Works great!
