### ISSUE TITLE
Error sending to Coveralls.io (422 - Unprocessable Entity

### ISSUE THREAD

**Issue by kbilsted** [coveralls-net/coveralls.net#8]
Currently I'm getting the following error message when sending to coveralls.

my configuration is https://github.com/kbilsted/StatePrinter/blob/feature/codecoverage/appveyor.yml

I had it working briefly earlier today but before i encrypted the token. Thus I've generated a new token and encrypted it. There really are no hints as to what is wrong. From the overalls pages I've gathered that it may be lack of environment variables. I've double checked against your example `.yml` with no success of tracking the problem

```
Visited Classes 81 of 91 (89.01) 
Visited Methods 288 of 313 (92.01) 
Visited Points 1286 of 1412 (91.08) 
Visited Branches 579 of 671 (86.29) 

==== Alternative Results (includes all methods including those without corresponding source) ==== 
Alternative Visited Classes 95 of 102 (93.14) 
Alternative Visited Methods 358 of 397 (90.18) 
C:\projects\stateprinter\packages\coveralls.io.1.1.86\tools\coveralls.net.exe --opencover coverage.xml
Service: appveyor
 Job ID: mp8v1nv2ygiqpkks
  Files: 48
 Commit: df985b6d56b7d60269545751b202afae37135920
Error sending to Coveralls.io (422 - Unprocessable Entity
```
1. do you have an idea?
2. can we improve the error message? It looks as though information is being cut off.

**Comment by jdeering** [comment]
From what I remember it's an error returned from coveralls. I'll look into it early this week. Any more information you happen across regarding this error can be posted here.

**Comment by kbilsted** [comment]
Hi Thanks for the quick reply

I've just tried the unencrypted token approach again alas with the same result. Was woring around 5-7 hours ago. Maybe they've changed something? Currently, I'm only running this off appveyor. Maybe I should attempt running locally

**Comment by kbilsted** [comment]
Just tried running it locally. It worked fine

```
>> packages\OpenCover.4.5.3522\OpenCover.Console.exe -register:user -filter:"+[StatePrinter.Tests*]*" -target:".\packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"StatePrinter.Tests\bin\debug\StatePrinter.Tests.dll" -output:coverage.xml -log:all

$env:COVERALLS_REPO_TOKEN="JjCu65jaJJfW6PcNI5HwCkp7i32eGDtby"

>> packages\coveralls.io.1.1.86\tools\coveralls.net.exe --opencover coverage.xml
```

result at https://coveralls.io/builds/1888749

Weird meta data though (the commit message)

```
COMMITED 8 FEB 20 - 21:21 FIRST BUILD ON FEATURE/CODECOVERAGE AT 88.59%
COMMITED BY
2dc5e0adfd68623e31f14c6db4e93c15?size=18&default=identiconkbilsted  

COMMIT MESSAGE
unencrypt
```

I just did another commit and ran the above locally again. This time it worked fine with the commit message.

**Comment by kbilsted** [comment]
The problem was that I had manually set an environment variable with the same name in the config which apparently overrules the .yml file. I finally found out by adding a --debug flag to  coveralls.net and releasing my own nuget package. PR has been sent your way in #9
